### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by talantbekov123** [t0nyhat/formRegexValidation#1]
Добрый день, хорошая работа. К сожалению текущая реализация содержит ряд недостатков, не позволяющих мне засчитать работу на данной итерации.

**Надо исправить**
- В репозитории не указали версии. По умолчанию, команда git push не отправляет теги на удалённые сервера. После создания тегов нужно отправлять явно на удалённый сервер. Процесс аналогичен отправке веток — достаточно выполнить команду `git push origin <tagname>` или `git push origin --tags`. Подробнее можно ознакомиться [тут](https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BC%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8#r_git_tagging)
- Проверку проходит следующие некорректные адреса сайтов http://ya.ru:00000,  http://11.11.11.11:0000 (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html). Проверку проходит не корретный адрес: https:yandex.ru

**Можно лучше**
- Дополнительно включить в сет регулярки точки. Не проходит валидная почты с использованием точки. Например: yandex.staff@gmail.com, alex.lion@gmail.com, test.test@test.gmail.com, best.email@yandex.ru. Точка и дефис могут присутвовать в доменном имени и названии почты.
- Файлы logo.svg и cover.jpg, расположенные в репозитории не используются на странице (загружаются с серверов Яндекса). Просьба либо задействовать их либо удалить.
- Файл .gitignore содержит слишком много условий, вы можете потерять нужные файлы при отправке проекта в гитхаб. Несколько шаблонов .gitignore для javascript(https://gist.github.com/andreasonny83/b24e38b7772a3ea362d8e8d238d5a7bc) и nodejs(https://github.com/github/gitignore/blob/master/Node.gitignore).

**Comment by t0nyhat** [comment]
Ну начало положено и это уже хорошо. Буду дорабатывать.

**Comment by talantbekov123** [comment]
Отличная работа! Основные требования выполнены. Прошу исправить комментарии **Надо исправить** после чего смогу принять работу.

**Отлично**
- оформленное readme.md
- работа на github pages, все поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены

**Надо исправить**
- "EXAMPLE@привет" (email разрешается a-z)
- “den~test@gmail.com”, “den!s@gmail.com” -  Проходят валидацию не корректные адреса доп символами.
- "+7(925)900-90-9099" (на одну цифру больше чем положено),
- "+7(925)900-90-9" "+7(925)900-90-" "+7(925)900-90-" (на одну и более цифр меньше чем положено)
- "+7 925--900--90-90" (между секциями дефис должен встречаться только в одном экземпляре)
- "http://google.ru///1///2///3" (ссылка на сайт - количество слешей в пути должно быть ограничено одним экземпляром для каждой части пути),

**Comment by t0nyhat** [comment]
Эти регулярки можно шлифовать до бесконечности ,мне кажется ))

**Comment by talantbekov123** [comment]
Отличная работа! Принимаю работу!

**Отлично**
- оформленное readme.md
- работа на github pages, все поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены
